### PR TITLE
Use static URL to download assets from latest release

### PR DESCRIPTION
**Pull request by corneliusweig**
This also simplifies the release process for krew, because the version
number does not need to be updated when releasing a new version.

Fixes #...
Related issue: #...

### CODE REVIEW

**Comment by corneliusweig** [comment]
@ahmetb was there a particular reason why the version should be hardcoded and thus visible that I'm not aware of?

**Comment by ahmetb** [comment]
I think we didn’t know “latest” worked?
That said I don’t understand removing the tagging instructions in Releasing.md.

**Comment by corneliusweig** [comment]
Oh it's because for a release we needed to adjust the hardcoded version number in `README.md`. That change needed to be committed, pushed, built, and fetched. All of these steps can now be skipped. The tagging step is still there I hope :).

**Comment by ahmetb** [comment]
Hmm but we still need this:

           git commit -am "Release ${TAG:?TAG required}"	

This ensures we have a clean commit that tags the release (we can add `--allow-empty`). 

I frequently follow this pattern in my repos, it helps a lot in the GitHub web UI, as users go to a "commit" that explains the tag; not some irrelevant patch.

**Comment by corneliusweig** [comment]
Ok, that makes sense. Added the instructions for creating a release commit back in.

**Pull request merged**
