### PR TITLE
Refactor: move errorFetcher struct to test file

### PR DESCRIPTION
**Pull request by corneliusweig**
This fetcher was only used in its test.

### CODE REVIEW

**Comment by ahmetb** [comment]
It actually helps us have code coverage around error cases in downloader.
That's why it's there. :)
/hold

**Comment by ahmetb** [comment]
In other words, we ensure the errors from downloader implementation are returned correctly.

**Comment by corneliusweig** [comment]
Whoops .. sorry I wasn't thinking straight. Thanks for catching this. I do think however, that it should have been in the test file.
/retitle Refactor: move errorFetcher struct to test file

**Pull request merged**
