### PR TITLE
Add CLI for setting Windows path in readme

### PR DESCRIPTION
**Pull request by rbirkby**
Use ```setx``` DOS commandline to set per-user %PATH% environment variable  - [Windows docs](https://docs.microsoft.com/en-us/windows-server/administration/windows-commands/setx)

### CODE REVIEW

**Comment by ahmetb** [comment]
/hold
/assign

Problem is, that only takes effect in that command-line window, right?

We want users to launch system settings control panel and update the environment variable there.

**Comment by rbirkby** [comment]
No - using ```set``` only takes effect in the current DOS session (ie current shell) whereas ```setx``` affects the whole environment for new shells only - similar to adding to .bashrc.

I added a hold to this PR because setx for user-local PATH env can duplicate all entries because it merges both user-local and system PATH. That is unacceptable. Using /M switch can help but presents its own problems.

**Comment by ahmetb** [comment]
I think users should use the relevant Control Panel to do this, right?

Maybe we can link to a page showing how to do it in the UI?

**Comment by ahmetb** [comment]
I'll close this for now. Please let us know if you find a better solution. :)
/close

**Pull request closed without merging**
