### PR TITLE
Update install.md: Install via `brew`

### PR DESCRIPTION
**Pull request by guettli**
I think installing via brew is the most straight forward way and works on most OSs (Mac, Linux, WSL).

### CODE REVIEW

**Comment by ahmetb** [comment]
It's not a fair assumption that Homebrew is the most widely used package manager across distros. 

Separately, Krew installs and updates itself as a plugin. And we don't actively maintain the Brew formulae as part of our releases (Brew community does the upkeep of the formula.)

So I'm -1 on placing it on the top as the recommended way.

**Review by kundan2707 — COMMENTED** [review]
/lgtm

**Comment by guettli** [comment]
@ahmetb thank you for your feedback. I discovered that if I install via brew, then the shell autocomplete gets added automatically. AFAIK this is not possible with krew. At the moment I don't see a reason to use krew. I close the issue. But again, thank you for your feedback.

**Pull request closed without merging**
