### PR TITLE
Update golangci-lint to v1.21.0

### PR DESCRIPTION
**Pull request by ferhatelmas**
Incremental analysis is added.

### CODE REVIEW

**Comment by ferhatelmas** [comment]
There are some new linters; like whitespace (enforces using more whitespace). 

Should we evaluate them if we want to enable or not? To me, we have something stable and new ones have overlapping functionality with existing ones.

**Comment by corneliusweig** [comment]
> To me, we have something stable and new ones have overlapping functionality with existing ones.

If I understand this comment correctly, you are saying that you don't see the need to enable more linters. Is that correct?

**Comment by ferhatelmas** [comment]
Yes. 

In general, we can keep an eye for newcomers but for now, new ones are related to style and not needed, I think.

**Comment by corneliusweig** [comment]
I see. Thanks for keeping this up-to-date!
/lgtm
/approve

**Pull request merged**
