### PR TITLE
Add link to sample-cli-plugin in developer guide

### PR DESCRIPTION
**Pull request by chriskim06**
Let me know if the wording of this should be changed at all.

Fixes https://github.com/kubernetes-sigs/krew/issues/328

### CODE REVIEW

**Comment by ahmetb** [comment]
I think there are some changes we made to the sample-cli-plugin that aren’t merged still after such a long time. In that case we don’t need to link out until they’re merged.

**Comment by chriskim06** [comment]
Sounds good, should I just close this?

**Comment by ahmetb** [comment]
lets keep it open.
I'm thinking a major Developer Guide overhaul. Would be useful to incorporate there perhaps.
/lifecycle frozen

**Comment by ahmetb** [comment]
Honestly I think it's ok sample-cli-plugin doesn't mention Krew in this case.
Krew has enough momentum now.

/lgtm
/approve

**Pull request merged**
