### PR TITLE
fix version stamping in build script

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #...
Related issue: #...

### CODE REVIEW

**Comment by ahmetb** [comment]
cc: @tony-yang it seems like we're doing cmp.Diff here which is map equality, though it would probably be better to just make sure if the specified set of keys/values exist in the output (instead of exact match)

**Comment by ahmetb** [comment]
/hold
until #497; then rebase.

**Comment by corneliusweig** [comment]
Thanks for finding this bug.
/lgtm
/approve

**Comment by tony-yang** [comment]
> cc: @tony-yang it seems like we're doing cmp.Diff here which is map equality, though it would probably be better to just make sure if the specified set of keys/values exist in the output (instead of exact match)

Fair point. Thanks Ahmet.

**Pull request merged**
