### PR TITLE
Use tagged temp dirs to simplify cleanup

### PR DESCRIPTION
**Pull request by corneliusweig**
Fixes #...
Related issue: #...

### CODE REVIEW

**Comment by ahmetb** [comment]
/tmp shouldn't really need cleanup? :D Isn't that OS responsibility?

**Comment by corneliusweig** [comment]
It is, but usually (at least on my system) it's only done on reboot. And I don't boot frequently O_o

**Comment by ahmetb** [comment]
why don't you just add `&& rm -rf $KREW_ROOT` to the script? that's much easier?

**Comment by corneliusweig** [comment]
I think `KREW_ROOT` is not available anymore in the command after `&&`?

**Comment by ahmetb** [comment]
eh, you're right.

**Pull request merged**
