### PR TITLE
detect download failures when status code > 200

### LINKED ISSUE #819: download failures are interpreted as checksum mismatch
The krew client ignores the status code. This results in misleading errors that show a checksum mismatch when in fact the artifact was never downloaded. According to the go documentation:

```A non-2xx response doesn't cause an error```

### PR DESCRIPTION
**Pull request by daniel-garcia**
detect download failures when status code is > 200
#819

### CODE REVIEW

**Comment by ahmetb** [comment]
Thanks for this patch, sorry it didn't catch my attention earlier. Can we also add a test case (with a httptest server responding with 404 ) to validate this doesn't regress?

**Comment by daniel-garcia** [comment]
> Thanks for this patch, sorry it didn't catch my attention earlier. Can we also add a test case (with a httptest server responding with 404 ) to validate this doesn't regress?

done.

**Review by ankishagarwal — APPROVED** [review]

**Comment by ankishagarwal** [comment]
Can we complete this if all okay ? We need this change, thank you

**Comment by ahmetb** [comment]
/lgtm

thanks.

**Pull request merged**
