### PR TITLE
Trim and minify SVG assets

### LINKED ISSUE #533: logo: Crop logo assets to the content
Right now, the logo assets have some spacing around them. This isn't quite useful and is often an additional step for anyone using the logos. (Website navbar is a good example.)

It would be good to re-export the assets by cropping to content.

/cc @iboonox 
/priority P3

### PR DESCRIPTION
**Pull request by corneliusweig**
Fixes #533

### CODE REVIEW

**Comment by ahmetb** [comment]
What sort of tool did you use to do this? 🤔

**Comment by corneliusweig** [comment]
https://inkscape.org/ (has nice auto-trim) + https://jakearchibald.github.io/svgomg/ (lots of options to reduce size)

**Comment by ferhatelmas** [comment]
This might be enabled for the repo: https://github.com/marketplace/imgbot

**Comment by corneliusweig** [comment]
imgbot looks nice. I wonder if there's a k8s policy about what bots can be enabled?

**Comment by ahmetb** [comment]
Since we don’t get images on an ongoing basis we prob don’t need a bot.

**Pull request merged**
