### PR TITLE
Add ppc64le support

### PR DESCRIPTION
**Pull request by mgiessing**
Fixes #...
Related issue: #...

Added support for ppc64le architecture and therefore not really a feature content-wise

### CODE REVIEW

**Comment by prb112** [comment]
HI All, I'm a ppc64le user and would like to follow along on this work. Is there a thread to follow/discussion on updates?

**Comment by mgiessing** [comment]
@soltysh can you approve or tell me what needs to be changed in order to merge?

**Comment by ahmetb** [comment]
Sorry, I forgot to review this one. I don't know much about ppc architecture. Can you please explain how it is used on developer/operator machines where kubectl plugins would be installed? I'm trying to distinguish if it is more of a server architecture than it is for dev machines.

**Comment by prb112** [comment]
@ahmetb the ppc64le architecture is used as a foundation for OpenShift nodes.  The kubectl is used mainly by the operators to manage the environment from either a jump server/bastion server.  

I hope this helps. @mgiessing may have more to add/or a different view point.

**Comment by mgiessing** [comment]
You've brought it to the point! Besides OpenShift, ppc64le can of course also be used as the foundation for "vanilla" Kubernetes. As indicated by @prb112  kubectl is in this context mainly used by the operators of such a cluster. Since Power has a strong focus on Linux & open source this commit was part of the upstreaming work in kubespray to enable ppc64le along many of its components (e.g. krew).

**Comment by ahmetb** [comment]
Thanks for the explanation.

> The kubectl is used mainly by the operators to manage the environment from either a jump server/bastion server.

Do you think people actually install kubectl plugins (i.e. convenience tools) to the bastion/jump servers? Nearly none of the kubectl plugins are not thoroughly vetted from a security perspective and I am hoping people don't run plugins from their bastion servers.

This has no extra cost to us, but I'd love to really understand which plugins you'll install with this. Today, none of the plugins distribute for `ppc64le` and I believe [the only submission we ever got](https://github.com/kubernetes-sigs/krew-index/pull/1618) was from Red Hat, so I'm trying to ensure there's actually >1 users who need this.

**Comment by prb112** [comment]
Hi @ahmetb here is an example I hit today. I went to install the [minio operator](https://github.com/minio/operator/blob/master/README.md#minio-operator-and-kubectl-plugin), and it requires the krew plugin before I can install it. 

Many thanks, and I hope this helps further this PR

Paul

**Comment by ahmetb** [comment]
Thanks, yeah we should probably add. 
Also keep in mind that minio operator probably doesn't offer a binary for this platform because up until now, we didn't distribute krew for it. So those plugins have to update with the addition.

**Comment by mkumatag** [comment]
> Thanks, yeah we should probably add.
> Also keep in mind that minio operator probably doesn't offer a binary for this platform because up until now, we didn't distribute krew for it. So those plugins have to update their manifests here in krew-index.

@ahmetb wondering if we can merge this PR if no further comments?

**Comment by mkumatag** [comment]
@ahmetb any idea when this will get into the release?

**Pull request merged**
