### PR TITLE
Bump Go to 1.17

### PR DESCRIPTION
**Pull request by gliptak**
Signed-off-by: Gábor Lipták <gliptak@gmail.com>

Fixes #...
Related issue: #...

### CODE REVIEW

**Comment by corneliusweig** [comment]
This change will only run our test suite with the 1.17 Go release. Do you also want to switch the project to go 1.17 (by modifying `go.mod`)?

**Comment by gliptak** [comment]
@corneliusweig updated

**Comment by chriskim06** [comment]
I think maybe you want to change
```
goVer: [1.16, 1.17]
```
to just 
```
goVer: [1.17]
```

or maybe update how the test that's failing works. i haven't really looked into that yet

**Comment by gliptak** [comment]
@chriskim06 updated

**Comment by chriskim06** [comment]
guessing that command doesn't work here, I'm going to manually rerun these checks

**Comment by ahmetb** [comment]
I have re-triggered Netlify builds manually but if it continues to fail, feel free to merge manually. Idk what causes it to fail like this.

**Comment by ahmetb** [comment]
Let's merge and see how Netlify takes it. 
/lgtm
/approve

**Pull request merged**
