### PR TITLE
Add pull request template

### PR DESCRIPTION
**Pull request by corneliusweig**
When small PRs are opened they often contain only very little description about the issue. In particular, they

- don't reference existing issues
- don't set related issues to auto-close
- open PRs without issues

This template should help out to improve this. Also, it explicitly mentions tests, so we hopefully see more of those :)

### CODE REVIEW

**Comment by ahmetb** [comment]
I'm -1 b/c it's too long. I don't find the long PR/issue templates productive.


> * don't reference existing issues
> * don't set related issues to auto-close
> * open PRs without issues

If all you're trying to address is these points, this will do:

```
Fixes #...
Related issue: #...
```

**Comment by corneliusweig** [comment]
We can definitely shorten more. Another goal is to remind submitters to add test.

**Comment by ahmetb** [comment]
Lets not do checklists if we can. Not everything warrants a test, and we can easily say please add tests.

**Comment by ahmetb** [comment]
IMO lets not have any [ ] at all. I don’t want progress bars floating around for no good reason. Most people don’t even know GFM has that feature. If we can cap at 3 consecutive lines and no checkmarks I am happier.

**Comment by corneliusweig** [comment]
Alright let's keep it minimal then. It's anyway just restating what is in our contributor guidelines.

**Comment by ahmetb** [comment]
Do you mind removing empty lines. They aren’t required for newlines in PR descriptions.

**Comment by corneliusweig** [comment]
Right, I should have known :rofl:

**Comment by ahmetb** [comment]
/lgtm
/approve
Thanks!

**Pull request merged**
