### PR TITLE
hack/run-in-docker: refactoring

### PR DESCRIPTION
**Pull request by ahmetb**
- build krew binary outside container (do not duplicate build process)
  - allows binary to be refreshed without rebuilding container
    this way, we preserve container session/state
  - also good for not leaking unused images to docker engine
    that needs to be cleaned up regularly
- mount KUBECONFIG inside the container (not sure if it's actually useful)
  I probably won't use it (since GKE clusters require gcloud to work, too)
- made the script a bit friendlier to follow as a user.

### CODE REVIEW

**Comment by corneliusweig** [comment]
Could you change the runtime image to something other than alpine? That was a bad idea, because whenever something needs a `libc`, there's only `libc.musl`.
What about `gcr.io/gcp-runtimes/ubuntu_16_0_4`?

**Comment by ahmetb** [comment]
> What about `gcr.io/gcp-runtimes/ubuntu_16_0_4`?

We can do that. Is there a reason why we should still have `go` in this image?

**Comment by corneliusweig** [comment]
> Is there a reason why we should still have `go` in this image?

The builder image needs it, but the final image with the krew binary inside has no `go` toolchain. Or do I misunderstand your question?

**Comment by ahmetb** [comment]
I'm afraid you didn't read the PR description. (:

> * build krew binary outside container (do not duplicate build process)
>   
>   * allows binary to be refreshed without rebuilding container
>     this way, we preserve container session/state

we don't need Go inside the container.

**Comment by corneliusweig** [comment]
> I'm afraid you didn't read the PR description.

Yes, that's right. I was only sharing the improved version of the former Dockerfile. With your improvements that will no longer be necessary.

**Comment by ahmetb** [comment]
@corneliusweig are you actually using this script?
I'm planning on fixing the PR, but not sure about the use case.

**Comment by corneliusweig** [comment]
@ahmetb Yes, whenever I want to review a new submission to krew-index, I try to install and run it inside docker. That's my main use-case.

**Comment by ahmetb** [comment]
/assign @corneliusweig 
sorry just got to this!

**Comment by corneliusweig** [comment]
Beautiful! Works like a charm. :unicorn:

/lgtm
/approve

**Comment by corneliusweig** [comment]
/lgtm cancel

Can you change the PR title?

**Comment by corneliusweig** [comment]
/lgtm
Prow won't merge anyway until the title is fixed.

**Pull request merged**
