### PR TITLE
Set up Travis CI for release binaries

### LINKED ISSUE #337: Go 1.13 breaks 'go test' flags, possibly conflicting with glog flags
Due to a change in go 1.13 the `go test -short` or `go test -v` flags no longer work. This is happening primarily because we are registering our own flags.

This happened as I bumped to go1.13 in #334. (Go is tracking at https://github.com/golang/go/issues/31859)

Other projects with similar stacks are also impacted:
- Knative: https://github.com/knative/test-infra/issues/1329
- Istio: https://github.com/istio/istio/issues/16797

In our case, currently this is borking out at `go test -short` that's listed in .travis.yml on `cmd/validate-krew-manifest` (a program that registers flag using glog):

```
$ go test -short -coverprofile=coverage.txt -covermode=atomic ./...
?   	sigs.k8s.io/krew/cmd/krew	[no test files]
?   	sigs.k8s.io/krew/cmd/krew/cmd	[no test files]
?   	sigs.k8s.io/krew/cmd/krew/cmd/internal	[no test files]
flag provided but not defined: -test.short
Usage of /tmp/go-build724846101/b189/validate-krew-manifest.test:
  -alsologtostderr
    	log to standard error as well as files
  -log_backtrace_at value
    	when logging hits line file:N, emit a stack trace
  -log_dir string
    	If non-empty, write log files in this directory
  -logtostderr
    	log to standard error instead of files
  -manifest string
    	path to plugin manifest file
  -stderrthreshold value
    	logs at or above this threshold go to stderr
  -v value
    	log level for V logs
  -vmodule value
    	comma-separated list of pattern=N settings for file-filtered logging
FAIL	sigs.k8s.io/krew/cmd/validate-krew-manifest	0.017s
ok  	sigs.k8s.io/krew/integration_test	0.017s	coverage: [no statements]
?   	sigs.k8s.io/krew/pkg/constants	[no test files]
ok  	sigs.k8s.io/krew/pkg/download	0.010s	coverage: 78.0% of statements
ok  	sigs.k8s.io/krew/pkg/environment	0.016s	coverage: 92.9% of statements
?   	sigs.k8s.io/krew/pkg/gitutil	[no test files]
?   	sigs.k8s.io/krew/pkg/index	[no test files]
ok  	sigs.k8s.io/krew/pkg/index/indexscanner	0.022s	coverage: 83.7% of statements
ok  	sigs.k8s.io/krew/pkg/index/validation	0.020s	coverage: 97.1% of statements
ok  	sigs.k8s.io/krew/pkg/info	0.030s	coverage: 100.0% of statements
ok  	sigs.k8s.io/krew/pkg/installation	0.015s	coverage: 39.9% of statements
ok  	sigs.k8s.io/krew/pkg/installation/receipt	0.011s	coverage: 83.3% of statements
ok  	sigs.k8s.io/krew/pkg/installation/semver	0.005s	coverage: 100.0% of statements
ok  	sigs.k8s.io/krew/pkg/pathutil	0.002s	coverage: 100.0% of statements
ok  	sigs.k8s.io/krew/pkg/receiptsmigration	0.010s	coverage: 50.0% of statements
ok  	sigs.k8s.io/krew/pkg/receiptsmigration/oldenvironment	0.010s	coverage: 93.8% of statements
?   	sigs.k8s.io/krew/pkg/testutil	[no test files]
ok  	sigs.k8s.io/krew/pkg/version	0.023s	coverage: 100.0% of statements
FAIL
```

I am not sure what the fix is, but I think we can block the release until we fix this.

/cc @ferhatelmas 
/cc @corneliusweig

### PR DESCRIPTION
**Pull request by ahmetb**
Ref: #324.
Ref: #333. 

Fixes #337.
/assign @corneliusweig

### CODE REVIEW

**Comment by corneliusweig** [comment]
As far as I can tell, this looks good. I only have little experience with releasing via travis on Github, though. Can we somehow test this before merging?

One minor nit: Before, we were building with `golang:alpine-1`, which uses golang 1.13 (see https://github.com/docker-library/golang/blob/2909cfd3ecb769671eb8222eaf9a782a6aed024d/1.13/alpine3.10/Dockerfile). On Travis, we are still using golang 1.11. Can we bump that for our travis builds?

**Comment by corneliusweig** [comment]
PS: It would make sense to adapt `hack/make-release-notes.sh` with the new download URLs for the krew artifacts.

**Comment by ahmetb** [comment]
I've tagged a v0.3.0-rc.1 with this commit. I've manually marked it as pre-release.
Sadly, there's still no clean way to auto-populate release message (#122) but it works.

**Comment by ahmetb** [comment]
Addressed comments.

**Comment by ahmetb** [comment]
I'm getting some weird errors after switching `go: 1.13.x`, might go back to 1.11.x.

image

**Comment by corneliusweig** [comment]
/lgtm
/approve
Big :+1: for getting the migration to Travis done so quickly AND fixing this strange `flags.Parse()` bug.

**Comment by corneliusweig** [comment]
Btw, with github releases we can get the number of downloads pretty easily:

```sh
curl -sLH 'Accept: application/vnd.github.v3+json' "https://api.github.com/repos/kubernetes-sigs/krew/releases" | \
        jq 'map([{key: "release", value: .tag_name}, {key: "assets", value: ( .assets | map({key: .name, value: .download_count}) | from_entries )}]|from_entries) '
```

At least we will know how many users upgraded krew :)

**Comment by ahmetb** [comment]
Exactly my thoughts.

I wish we had an app that monitored that endpoint it over time so we could tell the delta by {day, month, year} to do some analytics.

I have developed https://gh-downloads-dpyb4duzqq-uc.a.run.app/grpc-ecosystem/grpc-health-probe many months ago but it doesn't have any sort of persistent storage.

**Pull request merged**
