### PR TITLE
Update README.md - install krew with homebrew

### PR DESCRIPTION
**Pull request by arslanbekov**
I think many people be happy to install `krew` with homebrew.
I just add this in README.md

### CODE REVIEW

**Comment by arslanbekov** [comment]
Ok, no problem.
Thanks for clarifying @corneliusweig

**Comment by ahmetb** [comment]
Oh no. 
We can’t support that installation method as krew is supposed to install and update itself. 

@corneliusweig can you take up the task of working with Brew maintainers to remove Krew from Homebrew formula list? Maybe we can detect and refuse to work as well but that’s not preferable.

**Comment by immae1** [comment]
@corneliusweig could you please explain how i could update the path for the brew installed krew? I need the brew installation because i install some other plugins for docker with a ansible playbook. I will keep this simple

**Comment by corneliusweig** [comment]
@immae1 Oh no.. looks like homebrew is still distributing the old version v0.3.3.  Otherwise you would have seen a warning what to do.

Basically you need to do step three from our installation instructions https://github.com/kubernetes-sigs/krew/#installation

**Pull request closed without merging**
