### PR TITLE
lint: simplify scripts while formatting

### PR DESCRIPTION
**Pull request by ferhatelmas**
simplify shell scripts while formatting similar to `gofmt -s`.

### CODE REVIEW

**Comment by ahmetb** [comment]
Let's not do this. It intervenes with the style quite a bit.

**Comment by ahmetb** [comment]
All it seems to do is to just unquote variables when they're used inside `[` or `[[`. There's no harm in using double quotes for strings in `[` and `[[` (numbers are a different story).

**Comment by ferhatelmas** [comment]
> Let's not do this. It intervenes with the style quite a bit.

I thought creating an issue to discuss at first but then did since it was tiny.

Closing then?

**Comment by ahmetb** [comment]
Yeah, the value add is very small.
/close

**Pull request closed without merging**
