### PR TITLE
lint: bump golangci-lint to 1.18

### PR DESCRIPTION
**Pull request by ferhatelmas**
bump golangci-lint to 1.18, various improvement and go 1.13

related #334

### CODE REVIEW

**Comment by ahmetb** [comment]
Is this bump specifically addressing the issue we're seeing at #334?

**Comment by ahmetb** [comment]
Just saw your note, let's take it in, and I'll rebase #334.
/lgtm
/approve

**Comment by ahmetb** [comment]
Thanks, it seems like it has helped unblock switching to go1.13 in #334.

**Comment by ferhatelmas** [comment]
glad to see it helped :smiley_cat:

**Pull request merged**
