### PR TITLE
docs(README.md): Remove Travis CI badge and use GitHub CI badge

### LINKED ISSUE #651: Remove Travis CI badge from README, use GitHub CI badge
/good-first-issue
/help-wanted

### PR DESCRIPTION
**Pull request by akwanmaroso**
Fixes #651 
Hi, i just create pr to fixes issue #651

### CODE REVIEW

**Comment by akwanmaroso** [comment]
I signed it

**Comment by akwanmaroso** [comment]
hi, please review my pr /assign @corneliusweig

**Comment by akwanmaroso** [comment]
hi, please review my pr /assign @corneliusweig

**Comment by akwanmaroso** [comment]
I signed it

**Comment by ahmetb** [comment]
/lgtm
/approve
Thank you. 🙏

**Pull request merged**
