### PR TITLE
Support linux/arm64 release

### LINKED ISSUE #673: Doesn't install on arm64
I tried using krew using the script from the [installation documentation](https://krew.sigs.k8s.io/docs/user-guide/setup/install/) on an RPi4.
```
(
  set -x; cd "$(mktemp -d)" &&
  curl -fsSLO "https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz" &&
  tar zxvf krew.tar.gz &&
  KREW=./krew-"$(uname | tr '[:upper:]' '[:lower:]')_$(uname -m | sed -e 's/x86_64/amd64/' -e 's/arm.*$/arm/')" &&
  "$KREW" install krew
)
```

Output
```
++ mktemp -d
+ cd /tmp/tmp.DXwzAkWdyQ
+ curl -fsSLO https://github.com/kubernetes-sigs/krew/releases/latest/download/krew.tar.gz
+ tar zxvf krew.tar.gz
./LICENSE
./krew-darwin_amd64
./krew-linux_amd64
./krew-linux_arm
./krew-windows_amd64.exe
++ uname
++ tr '[:upper:]' '[:lower:]'
++ uname -m
++ sed -e s/x86_64/amd64/ -e 's/arm.*$/arm/'
+ KREW=./krew-linux_aarch64
+ ./krew-linux_aarch64 install krew
bash: ./krew-linux_aarch64: No such file or directory
```
I know that there isn't an `arm64/aarch64` executable in the release packages, but it does seem to work by manually running `./krew-linux_arm install krew`

```
$ cat /etc/os-release 
PRETTY_NAME="Debian GNU/Linux 10 (buster)"
NAME="Debian GNU/Linux"
VERSION_ID="10"
VERSION="10 (buster)"
VERSION_CODENAME=buster
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```
```
$ uname -a
Linux pi-04 5.4.72-v8+ #1356 SMP PREEMPT Thu Oct 22 13:58:52 BST 2020 aarch64 GNU/Linux
```

### LINKED ISSUE #688: install: uses "arm" as arch selector on "arm64" devices
On an `arm64` device (per `go env GOARCH`), Krew successfully installs plugins with selector `arch: arm` however it doesn't install plugins with `arch: arm64`.

So I suspect there's something wrong with how we interpret os/arch pairs on arm64 specifically.

For example, installing krew itself (logs with -v=7 show) that Krew shows that it's picking up `arm` as the GOARCH value:

```
I0202 18:58:30.467003    2591 platform.go:43] Matching platform for labels(arch=arm,os=linux)
I0202 18:58:30.467073    2591 platform.go:51] Found matching platform with index (2)
```

/area distribution
/kind bug
/priority P2

### PR DESCRIPTION
**Pull request by ahmetb**
Fixes #673
Fixes #688

### CODE REVIEW

**Comment by corneliusweig** [comment]
/lgtm
/hold
For thoughts from @chriskim06

**Comment by chriskim06** [comment]
This seems fine to me, I only see 2 plugins (`passman` and `doctor`) that would be affected by this I think. Should we file issues in their repos or something to let them know about this change?

**Comment by ahmetb** [comment]
> This seems fine to me, I only see 2 plugins (`passman` and `doctor`) that would be affected by this I think. Should we file issues in their repos or something to let them know about this change?

Yeah sounds good, that would be great if you can open those issues.

I'll go ahead and merge this.

/hold cancel

**Pull request merged**
