### PR TITLE
Update README.md for krew v0.3.0

### PR DESCRIPTION
**Pull request by corneliusweig**
This PR is a workaround for the failed push to master, see https://github.com/kubernetes-sigs/krew/issues/324#issuecomment-528763309

### CODE REVIEW

**Comment by corneliusweig** [comment]
/hold
As the release is not completed.

**Comment by ahmetb** [comment]
@corneliusweig can you update the binary URLs in README.md + rebase?
Then we can merge this and tag it as v0.3.0 (manually) then push.

**Comment by ahmetb** [comment]
I also suspect that we need to update our RELEASING.md to point out that the commit must be approved first to make a _stable_ release with it?

**Comment by ahmetb** [comment]
/lgtm
/approve
💣 Fire in the hole! 🌩

**Pull request merged**
