### PR TITLE
Drop GOPROXY since same with default

### PR DESCRIPTION
**Pull request by ferhatelmas**
related to #388.

### CODE REVIEW

**Comment by ferhatelmas** [comment]
I formatted yaml too but it might be done separately or should be reverted (might be our desired format)?

**Comment by corneliusweig** [comment]
The original version is what the `travis-cli` produces. This will avoid further formatting changes in the future, so it would be best if you can make the change without re-formatting in a new way.

**Comment by ferhatelmas** [comment]
OK, reverted formatting.

**Comment by ahmetb** [comment]
I'm not at all sure why but this speeds up builds by 20 seconds.

old:

image


new:

image


/lgtm
/approve

**Comment by ferhatelmas** [comment]
> I'm not at all sure why but this speeds up builds by 20 seconds.

Recent builds are again back to slow speed. I also tried to find an explanation but I couldn't come up with a doc. I guess it was just network variance :open_mouth:

**Pull request merged**
